devtools::load_all(".")
m <- dsge_model(obs(y ~ z), state(z ~ rho * z), start = list(rho = 0.8))
sol <- solve_dsge(m, params = c(rho = 0.8), shock_sd = c(z = 1.0))
cat("H:", sol$H, "\n")
cat("G:", sol$G, "\n")
cat("M:", sol$M, "\n")

pf <- perfect_foresight(sol, shocks = list(z = 1.0), horizon = 5)
cat("States:\n")
print(pf$states)
cat("\nExpected: 1.0, 0.8, 0.64, 0.512, 0.4096\n")
cat("  (rho^1, rho^2, rho^3, rho^4, rho^5)\n")
cat("Or: 1.0, 0.8, 0.64, 0.512, 0.4096\n")
cat("  (M*1, H*M*1, H^2*M*1, ...)\n")
