// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lyapunov_schur_cpp
List lyapunov_schur_cpp(const arma::mat& H, const arma::mat& Q);
RcppExport SEXP _dsge_lyapunov_schur_cpp(SEXP HSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(lyapunov_schur_cpp(H, Q));
    return rcpp_result_gen;
END_RCPP
}
// kalman_filter_cpp
List kalman_filter_cpp(const arma::mat& y, const arma::mat& Z, const arma::mat& H, const arma::mat& Q, const arma::mat& P0, int presample, bool store);
RcppExport SEXP _dsge_kalman_filter_cpp(SEXP ySEXP, SEXP ZSEXP, SEXP HSEXP, SEXP QSEXP, SEXP P0SEXP, SEXP presampleSEXP, SEXP storeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< int >::type presample(presampleSEXP);
    Rcpp::traits::input_parameter< bool >::type store(storeSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_filter_cpp(y, Z, H, Q, P0, presample, store));
    return rcpp_result_gen;
END_RCPP
}
// kalman_filter_dynare_cpp
List kalman_filter_dynare_cpp(const arma::mat& y, const arma::mat& Z, const arma::mat& Tm, const arma::mat& RQR, const arma::mat& Hm, const arma::mat& P0, int presample);
RcppExport SEXP _dsge_kalman_filter_dynare_cpp(SEXP ySEXP, SEXP ZSEXP, SEXP TmSEXP, SEXP RQRSEXP, SEXP HmSEXP, SEXP P0SEXP, SEXP presampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RQR(RQRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Hm(HmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< int >::type presample(presampleSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_filter_dynare_cpp(y, Z, Tm, RQR, Hm, P0, presample));
    return rcpp_result_gen;
END_RCPP
}
// cyclic_reduction_cpp
List cyclic_reduction_cpp(const arma::mat& Am, const arma::mat& Az, const arma::mat& Ap, double tol, int max_it);
RcppExport SEXP _dsge_cyclic_reduction_cpp(SEXP AmSEXP, SEXP AzSEXP, SEXP ApSEXP, SEXP tolSEXP, SEXP max_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Am(AmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Az(AzSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    rcpp_result_gen = Rcpp::wrap(cyclic_reduction_cpp(Am, Az, Ap, tol, max_it));
    return rcpp_result_gen;
END_RCPP
}
// contract2_cpp
arma::mat contract2_cpp(const IntegerVector& eq, const IntegerVector& i, const IntegerVector& j, const NumericVector& v, const arma::mat& P, const arma::mat& Q, int n_eq);
RcppExport SEXP _dsge_contract2_cpp(SEXP eqSEXP, SEXP iSEXP, SEXP jSEXP, SEXP vSEXP, SEXP PSEXP, SEXP QSEXP, SEXP n_eqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type eq(eqSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j(jSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type n_eq(n_eqSEXP);
    rcpp_result_gen = Rcpp::wrap(contract2_cpp(eq, i, j, v, P, Q, n_eq));
    return rcpp_result_gen;
END_RCPP
}
// contract3_cpp
arma::mat contract3_cpp(const IntegerVector& eq, const IntegerVector& i, const IntegerVector& j, const IntegerVector& l, const NumericVector& v, const arma::mat& P, const arma::mat& Q, const arma::mat& R, int n_eq);
RcppExport SEXP _dsge_contract3_cpp(SEXP eqSEXP, SEXP iSEXP, SEXP jSEXP, SEXP lSEXP, SEXP vSEXP, SEXP PSEXP, SEXP QSEXP, SEXP RSEXP, SEXP n_eqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type eq(eqSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j(jSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n_eq(n_eqSEXP);
    rcpp_result_gen = Rcpp::wrap(contract3_cpp(eq, i, j, l, v, P, Q, R, n_eq));
    return rcpp_result_gen;
END_RCPP
}
// apply_hx_cpp
arma::mat apply_hx_cpp(const arma::mat& X, const arma::mat& hx, int k);
RcppExport SEXP _dsge_apply_hx_cpp(SEXP XSEXP, SEXP hxSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_hx_cpp(X, hx, k));
    return rcpp_result_gen;
END_RCPP
}
// sylvester_doubling_cpp
List sylvester_doubling_cpp(arma::mat P, const arma::mat& X, arma::mat hx, int k, double tol, int max_it);
RcppExport SEXP _dsge_sylvester_doubling_cpp(SEXP PSEXP, SEXP XSEXP, SEXP hxSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP max_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    rcpp_result_gen = Rcpp::wrap(sylvester_doubling_cpp(P, X, hx, k, tol, max_it));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dsge_lyapunov_schur_cpp", (DL_FUNC) &_dsge_lyapunov_schur_cpp, 2},
    {"_dsge_kalman_filter_cpp", (DL_FUNC) &_dsge_kalman_filter_cpp, 7},
    {"_dsge_kalman_filter_dynare_cpp", (DL_FUNC) &_dsge_kalman_filter_dynare_cpp, 7},
    {"_dsge_cyclic_reduction_cpp", (DL_FUNC) &_dsge_cyclic_reduction_cpp, 5},
    {"_dsge_contract2_cpp", (DL_FUNC) &_dsge_contract2_cpp, 7},
    {"_dsge_contract3_cpp", (DL_FUNC) &_dsge_contract3_cpp, 9},
    {"_dsge_apply_hx_cpp", (DL_FUNC) &_dsge_apply_hx_cpp, 3},
    {"_dsge_sylvester_doubling_cpp", (DL_FUNC) &_dsge_sylvester_doubling_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dsge(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
