// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lyapunov_schur_cpp
List lyapunov_schur_cpp(const arma::mat& H, const arma::mat& Q);
RcppExport SEXP _dsge_lyapunov_schur_cpp(SEXP HSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(lyapunov_schur_cpp(H, Q));
    return rcpp_result_gen;
END_RCPP
}
// kalman_filter_cpp
List kalman_filter_cpp(const arma::mat& y, const arma::mat& Z, const arma::mat& H, const arma::mat& Q, const arma::mat& P0, int presample, bool store);
RcppExport SEXP _dsge_kalman_filter_cpp(SEXP ySEXP, SEXP ZSEXP, SEXP HSEXP, SEXP QSEXP, SEXP P0SEXP, SEXP presampleSEXP, SEXP storeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< int >::type presample(presampleSEXP);
    Rcpp::traits::input_parameter< bool >::type store(storeSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_filter_cpp(y, Z, H, Q, P0, presample, store));
    return rcpp_result_gen;
END_RCPP
}
// kalman_filter_dynare_cpp
List kalman_filter_dynare_cpp(const arma::mat& y, const arma::mat& Z, const arma::mat& Tm, const arma::mat& RQR, const arma::mat& Hm, const arma::mat& P0, int presample);
RcppExport SEXP _dsge_kalman_filter_dynare_cpp(SEXP ySEXP, SEXP ZSEXP, SEXP TmSEXP, SEXP RQRSEXP, SEXP HmSEXP, SEXP P0SEXP, SEXP presampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RQR(RQRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Hm(HmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< int >::type presample(presampleSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_filter_dynare_cpp(y, Z, Tm, RQR, Hm, P0, presample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dsge_lyapunov_schur_cpp", (DL_FUNC) &_dsge_lyapunov_schur_cpp, 2},
    {"_dsge_kalman_filter_cpp", (DL_FUNC) &_dsge_kalman_filter_cpp, 7},
    {"_dsge_kalman_filter_dynare_cpp", (DL_FUNC) &_dsge_kalman_filter_dynare_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_dsge(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
