# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lyapunov_schur_cpp <- function(H, Q) {
    .Call(`_dsge_lyapunov_schur_cpp`, H, Q)
}

kalman_filter_cpp <- function(y, Z, H, Q, P0, presample, store) {
    .Call(`_dsge_kalman_filter_cpp`, y, Z, H, Q, P0, presample, store)
}

kalman_filter_dynare_cpp <- function(y, Z, Tm, RQR, Hm, P0, presample) {
    .Call(`_dsge_kalman_filter_dynare_cpp`, y, Z, Tm, RQR, Hm, P0, presample)
}

cyclic_reduction_cpp <- function(Am, Az, Ap, tol, max_it) {
    .Call(`_dsge_cyclic_reduction_cpp`, Am, Az, Ap, tol, max_it)
}

contract2_cpp <- function(eq, i, j, v, P, Q, n_eq) {
    .Call(`_dsge_contract2_cpp`, eq, i, j, v, P, Q, n_eq)
}

contract3_cpp <- function(eq, i, j, l, v, P, Q, R, n_eq) {
    .Call(`_dsge_contract3_cpp`, eq, i, j, l, v, P, Q, R, n_eq)
}

apply_hx_cpp <- function(X, hx, k) {
    .Call(`_dsge_apply_hx_cpp`, X, hx, k)
}

sylvester_doubling_cpp <- function(P, X, hx, k, tol, max_it) {
    .Call(`_dsge_sylvester_doubling_cpp`, P, X, hx, k, tol, max_it)
}

