# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lyapunov_schur_cpp <- function(H, Q) {
    .Call(`_dsge_lyapunov_schur_cpp`, H, Q)
}

kalman_filter_cpp <- function(y, Z, H, Q, P0, presample, store) {
    .Call(`_dsge_kalman_filter_cpp`, y, Z, H, Q, P0, presample, store)
}

kalman_filter_dynare_cpp <- function(y, Z, Tm, RQR, Hm, P0, presample) {
    .Call(`_dsge_kalman_filter_dynare_cpp`, y, Z, Tm, RQR, Hm, P0, presample)
}

