# Dynamic forecasting for DSGE models

#' Forecast from a Fitted DSGE Model
#'
#' Produces dynamic multi-step forecasts from a fitted DSGE model.
#' Forecasts are generated by iterating the state-space solution forward
#' from the last filtered state.
#'
#' @param object A `dsge_fit` object.
#' @param horizon Integer. Number of periods to forecast ahead. Default is 12.
#' @param ... Additional arguments (currently unused).
#'
#' @return An object of class `"dsge_forecast"` containing:
#'   \describe{
#'     \item{forecasts}{Data frame with columns `period`, `variable`, `value`.}
#'     \item{horizon}{The forecast horizon.}
#'     \item{states}{Matrix of forecasted state vectors.}
#'   }
#'
#' @export
forecast.dsge_fit <- function(object, horizon = 12L, ...) {
  sol <- object$solution

  if (!sol$stable) {
    stop("Cannot forecast from an unstable model.", call. = FALSE)
  }

  G <- sol$G
  H <- sol$H
  D <- sol$D

  # Get last filtered state
  n_T <- nrow(object$kalman$filtered_states)
  x_last <- object$kalman$filtered_states[n_T, ]

  obs_vars <- object$model$variables$observed
  n_obs <- length(obs_vars)
  Z <- D %*% G

  # Iterate forward (no shocks in forecast period)
  forecasted_obs <- matrix(0, horizon, n_obs)
  forecasted_states <- matrix(0, horizon, length(x_last))
  x_current <- x_last

  for (h in seq_len(horizon)) {
    x_current <- as.numeric(H %*% x_current)
    y_current <- as.numeric(Z %*% x_current)
    forecasted_states[h, ] <- x_current
    forecasted_obs[h, ] <- y_current
  }

  # Add back data means
  forecasted_obs <- sweep(forecasted_obs, 2, object$data_means)

  colnames(forecasted_obs) <- obs_vars

  # Build tidy data frame
  fc_list <- list()
  for (j in seq_along(obs_vars)) {
    fc_list[[j]] <- data.frame(
      period = seq_len(horizon),
      variable = obs_vars[j],
      value = forecasted_obs[, j],
      stringsAsFactors = FALSE
    )
  }
  fc_df <- do.call(rbind, fc_list)

  structure(
    list(
      forecasts = fc_df,
      horizon = horizon,
      states = forecasted_states,
      obs_matrix = forecasted_obs
    ),
    class = "dsge_forecast"
  )
}
